blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC Discord Support"
    url: https://discord.gg/pTErYjTh5h
    about: For quick questions and support, join our Discord server.
  - name: "\U0001F4D6 Documentation"
    url: https://skyxnetwork.net
    about: Check the website for documentation and guides.
